name: Reusable workflow

on:
  workflow_call

jobs:
 
  job:
    runs-on: ubuntu-latest
    steps:
     - run: |
          echo Add other actions to build,
          echo test, and deploy your project.
